config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  get '/admin/chats', to: 'admin/chats#load_chat_listing', as: :admin_chats_default
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :chats, only: [:create]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  include UserChatAssociations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
# app/models/chat.rb
class Chat < ApplicationRecord
  include ChatHelper
  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  validates :message, presence: true
  #after create commit broadcast
  after_create_commit :broadcast_message

  private

  def broadcast_message
    channel = generate_channel_name(sender, receiver)
    ActionCable.server.broadcast(channel, [self, sender.email] )
  end
end

app/models/concerns/user_chat_associations.rb
module UserChatAssociations
  extend ActiveSupport::Concern

  included do
    has_many :sent_chats, as: :sender, class_name: 'Chat', dependent: :destroy
    has_many :received_chats, as: :receiver, class_name: 'Chat', dependent: :destroy
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UserChatAssociations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/chats_controller.rb
module Api
    module V1
      class ChatsController < ApiController
  
        def create
            chat  = Chat.new(message: chat_params[:message])
            chat.sender = fetch_user(chat_params[:sender_type], chat_params[:sender_id])
            chat.receiver = fetch_user(chat_params[:receiver_type], chat_params[:receiver_id])
            if chat.save
                render json: {message: 'message sent'}, status: :ok
            else
                render json: {message: 'message failed'}, status: :bad_request
            end
        end
  
        private
  
        def chat_params
          params.require(:chat).permit(:sender_id, :receiver_id, :receiver_type, :message, :sender_type)
        end

        def fetch_user(type, id)
            return AdminUser.find(id) if type == 'admin'
            
            User.find(id)
        end
      end
    end
  end
  

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/chat_helper.rb
module ChatHelper
  def generate_channel_name(sender, receiver)
    "ChatChannel_#{sender.class}_#{sender.id}_to_#{receiver.class}_#{receiver.id}"
  end
end

app/views/admin/chats/chat.html.erb
<head>
  <%= javascript_importmap_tags %>
</head>
<body>
  <div id="reply-container">
    <%= form_for :reply_message, url: {:action=>"reply_message"}, html: { multipart: true } do |f|%>
      <caption>Reply to the messages</caption>
      <%= f.hidden_field :receiver_id, :value => @user.id %>
      <%= f.hidden_field :receiver_type, :value => "user" %>
      <table>
        <th></th>
        <tr>
          <td>
            <%= f.text_field :message, :placeholder => "Enter Message" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.submit 'Reply' %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
  <div id="table-container">
    <div id="cabledata" data-user-id="<%= @user.id %>" data-admin-user-id="<%= current_admin_user.id %>"></div>
    <table>
      <thead>
        <tr>
          <th>Sender Name</th>
          <th>Message</th>
        </tr>
      </thead>
      <tbody id="chat-table-body">
        <% @messages.each do |message| %>
          <tr>
            <td><%= message.sender.email %></td>
            <td><%= message.message %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/admin/chats/user_listing.html.erb
<h2>Recent Chats</h2>
<% @users.each do |user| %>
  <li><%= link_to user.email, load_messages_admin_chats_path(user_id: user.id) %></li>
<% end %>